FROM python:3.11-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    redis \
    numpy \
    scikit-learn

# Copy project
COPY . .

EXPOSE 8000

CMD ["python", "cloud/master_controller.py", "worker", "8000", "worker-default"]
