events {
    worker_connections 1024;
}

http {
    upstream master {
        server master:8080;
    }

    upstream workers {
        least_conn;
        server worker:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://master;
        }

        location /worker/ {
            proxy_pass http://workers;
        }
    }
}
